### ISSUE TITLE
Slack channel for EIDF cluster

### ISSUE THREAD

**Issue by AntreasAntoniou** [uoe-eidf-cluster-users/eidf-epcc-cluster#18]
Hello everyone,

I made a slack server for us, so we can easily communicate and collaborate on anything relating to the cluster. From experience I know that with shared resources, it's often easy to resolve any issues before they even occur by just being aware of each other and being able to communicate any issues that we are having (which can include jobs being blocked by another persons jobs etc). Or altogether to be used by new users, or existing users trying to do something. 

https://join.slack.com/t/slack-czc7871/shared_invite/zt-1wmdgxikm-KTGKTHF2Ez1s0zS0lziF9g

Join me in here

**Comment by pminervini** [comment]
Added to the README!
