### ISSUE TITLE
Suggestions for instruction

### ISSUE THREAD

**Issue by saparina** [uoe-eidf-cluster-users/eidf-epcc-cluster#24]
1. [New User Login](https://github.com/uoe-eidf-cluster-users/eidf-epcc-cluster#new-user-login): It would be useful to add a note that an SSH key should be attached to the account on the EIDF Portal/SAFE in order to connect via ssh.

2. [Kubectl get nodes](https://github.com/uoe-eidf-cluster-users/eidf-epcc-cluster#kubectl-get-nodes): The command ```kubectl get nodes``` does not work, I got an answer from the EIDF Support that the node descriptors are disabled.

**Comment by pminervini** [comment]
@saparina thanks! can you please do the changes yourselves and then do a pull request? I'll merge it right away!

**Comment by pminervini** [comment]
@saparina just granted you write access -- can you close this issue when you are done with the edits please?

**Comment by saparina** [comment]
Great, thanks! I'll try to complete all the steps first. I want to [run a pod](https://github.com/uoe-eidf-cluster-users/eidf-epcc-cluster#run-a-pod) but this does not work without ```--validate=false```. Waiting for the answer from the EIDF Support.

**Comment by saparina** [comment]
@pminervini I created a [pull request](https://github.com/uoe-eidf-cluster-users/eidf-epcc-cluster/pull/25), feel free to edit it if you want. Closing the issue!
